version: '3.8'
services:
  dogenet:
    build:
      context: .
      dockerfile: Dockerfile.dogenet
    container_name: dogenet
    ports:
      - "8085:8085"
    volumes:
      - ./data/dogenet/data:/root/storage
  dogenet2:
    build:
      context: .
      dockerfile: Dockerfile.dogenet2
    container_name: dogenet2
    ports:
      - "8086:8086"
    volumes:
      - ./data/dogenet2/data:/root/storage
  # fractalengine:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.fractalengine
  #   container_name: fractalengine
  #   ports:
  #     - "8891:8891"
  #   volumes:
  #     - ./data/fractalengine/data:/root/storage
  #   depends_on:
  #     dogecoin:
  #       condition: service_healthy
  # dogecoin:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dogecoin
  #   container_name: dogecoin
  #   ports:
  #     - "22555:22555"
  #   volumes:
  #     - ./data/dogecoin/data:/root/storage
  #   healthcheck:
  #     test: [
  #       "CMD", "curl", "--silent", "--user", "test:test",
  #       "--data-binary", "{\"jsonrpc\":\"1.0\",\"id\":\"curltest\",\"method\":\"getblockchaininfo\",\"params\":[]}",
  #       "-H", "content-type: text/plain;", "http://127.0.0.1:22555"
  #     ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5