version: '3.8'
services:
  fractal-ui:
    build:
      context: .
      dockerfile: Dockerfile.fractaladmin
      args:
        DATABASE_URL: "file:/app/data/fractal-ui.db"
    ports:
      - "3030:3000" 
    environment:
      - FRACTAL_ENGINE_URL=http://fractalengine:8891
      - DATABASE_URL=file:/app/data/fractal-ui.db
    volumes:
      - sqlite-data:/app/data
    depends_on:
      fractalengine:
        condition: service_healthy
    restart: unless-stopped
    profiles: [frontend]
  dogenet:
    profiles: [deps]
    build:
      context: .
      dockerfile: Dockerfile.dogenet
    container_name: dogenet
    environment:
      - DOGE_NET_HANDLER=$DOGE_NET_HANDLER
    ports:
      - "8085:8085"
      - "8086:8086"
    volumes:
      - doge-sock:/tmp
    healthcheck:
      test: ["CMD", "test", "/tmp/dogenet.sock"]
      interval: 10s
      timeout: 5s
      retries: 10
  fractalengine:
    profiles: [fractal]
    build:
      context: .
      dockerfile: Dockerfile.fractalengine
    container_name: fractalengine
    ports:
      - "8891:8891"
    environment:
      - DATABASE_URL=sqlite:///root/storage/fractal-engine.db
    depends_on:
      dogecoin:
        condition: service_healthy
      dogenet:
        condition: service_healthy
    volumes:
      - doge-sock:/tmp
      - sqlite-fractalengine-data:/root/storage
    healthcheck:
      test: [
        "CMD", "curl", "--silent", "content-type: text/plain;", "http://127.0.0.1:8891/health"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
  dogecoin:
    profiles: [deps]
    build:
      context: .
      dockerfile: Dockerfile.dogecoin
    container_name: dogecoin
    ports:
      - "22556:22556"
    healthcheck:
      test: [
        "CMD", "curl", "--silent", "--user", "test:test",
        "--data-binary", "{\"jsonrpc\":\"1.0\",\"id\":\"curltest\",\"method\":\"getblockchaininfo\",\"params\":[]}",
        "-H", "content-type: text/plain;", "http://127.0.0.1:22556"
      ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sqlite-data:
    driver: local
  doge-sock:
    driver: local
  sqlite-fractalengine-data:
    driver: local
