FROM debian:latest
RUN apt update && apt upgrade -y && apt install -y curl gpg ca-certificates tar dirmngr
RUN curl -o dogecoin.tar.gz -Lk https://github.com/dogecoin/dogecoin/releases/download/v1.14.9/dogecoin-1.14.9-x86_64-linux-gnu.tar.gz
RUN tar -xvf dogecoin.tar.gz
RUN rm dogecoin.tar.gz
RUN install -m 0755 -o root -g root -t /usr/local/bin dogecoin-1.14.9/bin/*
EXPOSE 22556

COPY regtest.conf /dogecoin.conf
CMD ["dogecoind", "-printtoconsole", "-regtest", "-reindex-chainstate", "-min", "-splash=0", "-conf=/dogecoin.conf"]