sequenceDiagram
    participant Processor as Fractal Engine Processor
    participant Store as Fractal Store

loop Every 5 seconds
    Processor->>Store: Fetch Onchain transactions
    alt Is Mint Transaction
        Processor->>Store: Match Unconfirmed Mint with Onchain Transaction
        Processor->>Store: Save Mint
        Processor->>Store: Update Token Balance
        Processor->>Store: Delete Onchain Transaction
        Processor->>Store: Delete Unconfirmed Mint
    end
end