// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: pkg/protocol/invoices.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is what gets written to the OP_RETURN on the L1
type OnChainInvoiceMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version       int32  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SellerAddress string `protobuf:"bytes,2,opt,name=seller_address,json=sellerAddress,proto3" json:"seller_address,omitempty"`
	InvoiceHash   string `protobuf:"bytes,3,opt,name=invoice_hash,json=invoiceHash,proto3" json:"invoice_hash,omitempty"`
	MintHash      string `protobuf:"bytes,4,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	Quantity      int32  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *OnChainInvoiceMessage) Reset() {
	*x = OnChainInvoiceMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_invoices_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnChainInvoiceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainInvoiceMessage) ProtoMessage() {}

func (x *OnChainInvoiceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_invoices_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainInvoiceMessage.ProtoReflect.Descriptor instead.
func (*OnChainInvoiceMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_invoices_proto_rawDescGZIP(), []int{0}
}

func (x *OnChainInvoiceMessage) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OnChainInvoiceMessage) GetSellerAddress() string {
	if x != nil {
		return x.SellerAddress
	}
	return ""
}

func (x *OnChainInvoiceMessage) GetInvoiceHash() string {
	if x != nil {
		return x.InvoiceHash
	}
	return ""
}

func (x *OnChainInvoiceMessage) GetMintHash() string {
	if x != nil {
		return x.MintHash
	}
	return ""
}

func (x *OnChainInvoiceMessage) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// This is what gets gossiped + stored in the gossip mempool + confirmed_transactions
type InvoiceMessageEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      int32           `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Version   int32           `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Payload   *InvoiceMessage `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey string          `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature string          `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *InvoiceMessageEnvelope) Reset() {
	*x = InvoiceMessageEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_invoices_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvoiceMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceMessageEnvelope) ProtoMessage() {}

func (x *InvoiceMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_invoices_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceMessageEnvelope.ProtoReflect.Descriptor instead.
func (*InvoiceMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_invoices_proto_rawDescGZIP(), []int{1}
}

func (x *InvoiceMessageEnvelope) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *InvoiceMessageEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *InvoiceMessageEnvelope) GetPayload() *InvoiceMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvoiceMessageEnvelope) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *InvoiceMessageEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type InvoicePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentAddress string `protobuf:"bytes,1,opt,name=payment_address,json=paymentAddress,proto3" json:"payment_address,omitempty"`
	BuyerAddress   string `protobuf:"bytes,2,opt,name=buyer_address,json=buyerAddress,proto3" json:"buyer_address,omitempty"`
	MintHash       string `protobuf:"bytes,4,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	Quantity       int32  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price          int32  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	SellerAddress  string `protobuf:"bytes,7,opt,name=seller_address,json=sellerAddress,proto3" json:"seller_address,omitempty"`
}

func (x *InvoicePayload) Reset() {
	*x = InvoicePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_invoices_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvoicePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoicePayload) ProtoMessage() {}

func (x *InvoicePayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_invoices_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoicePayload.ProtoReflect.Descriptor instead.
func (*InvoicePayload) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_invoices_proto_rawDescGZIP(), []int{2}
}

func (x *InvoicePayload) GetPaymentAddress() string {
	if x != nil {
		return x.PaymentAddress
	}
	return ""
}

func (x *InvoicePayload) GetBuyerAddress() string {
	if x != nil {
		return x.BuyerAddress
	}
	return ""
}

func (x *InvoicePayload) GetMintHash() string {
	if x != nil {
		return x.MintHash
	}
	return ""
}

func (x *InvoicePayload) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InvoicePayload) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *InvoicePayload) GetSellerAddress() string {
	if x != nil {
		return x.SellerAddress
	}
	return ""
}

type InvoiceMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash      string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Payload   *InvoicePayload        `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *InvoiceMessage) Reset() {
	*x = InvoiceMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_invoices_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvoiceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceMessage) ProtoMessage() {}

func (x *InvoiceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_invoices_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceMessage.ProtoReflect.Descriptor instead.
func (*InvoiceMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_invoices_proto_rawDescGZIP(), []int{3}
}

func (x *InvoiceMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvoiceMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *InvoiceMessage) GetPayload() *InvoicePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvoiceMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_pkg_protocol_invoices_proto protoreflect.FileDescriptor

var file_pkg_protocol_invoices_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x69,
	0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x66,
	0x72, 0x61, 0x63, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x01,
	0x0a, 0x15, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x6c, 0x6c, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x6d,
	0x69, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6d, 0x69, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x22, 0xbc, 0x01, 0x0a, 0x16, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x66, 0x72, 0x61, 0x63, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x49,
	0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x22, 0xd4, 0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x23, 0x0a, 0x0d, 0x62, 0x75, 0x79, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x75, 0x79, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x6c,
	0x6c, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xa8, 0x01, 0x0a, 0x0e, 0x49,
	0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x12, 0x37, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x66, 0x72, 0x61, 0x63, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_protocol_invoices_proto_rawDescOnce sync.Once
	file_pkg_protocol_invoices_proto_rawDescData = file_pkg_protocol_invoices_proto_rawDesc
)

func file_pkg_protocol_invoices_proto_rawDescGZIP() []byte {
	file_pkg_protocol_invoices_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_invoices_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_protocol_invoices_proto_rawDescData)
	})
	return file_pkg_protocol_invoices_proto_rawDescData
}

var file_pkg_protocol_invoices_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_protocol_invoices_proto_goTypes = []interface{}{
	(*OnChainInvoiceMessage)(nil),  // 0: fractalengine.OnChainInvoiceMessage
	(*InvoiceMessageEnvelope)(nil), // 1: fractalengine.InvoiceMessageEnvelope
	(*InvoicePayload)(nil),         // 2: fractalengine.InvoicePayload
	(*InvoiceMessage)(nil),         // 3: fractalengine.InvoiceMessage
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_pkg_protocol_invoices_proto_depIdxs = []int32{
	3, // 0: fractalengine.InvoiceMessageEnvelope.payload:type_name -> fractalengine.InvoiceMessage
	2, // 1: fractalengine.InvoiceMessage.payload:type_name -> fractalengine.InvoicePayload
	4, // 2: fractalengine.InvoiceMessage.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_protocol_invoices_proto_init() }
func file_pkg_protocol_invoices_proto_init() {
	if File_pkg_protocol_invoices_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_protocol_invoices_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnChainInvoiceMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_invoices_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvoiceMessageEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_invoices_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvoicePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_invoices_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvoiceMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_protocol_invoices_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_invoices_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_invoices_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_invoices_proto_msgTypes,
	}.Build()
	File_pkg_protocol_invoices_proto = out.File
	file_pkg_protocol_invoices_proto_rawDesc = nil
	file_pkg_protocol_invoices_proto_goTypes = nil
	file_pkg_protocol_invoices_proto_depIdxs = nil
}
