// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0--rc2
// source: pkg/protocol/invoices.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is what gets written to the OP_RETURN on the L1
type OnChainInvoiceMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SellOfferAddress string                 `protobuf:"bytes,2,opt,name=sell_offer_address,json=sellOfferAddress,proto3" json:"sell_offer_address,omitempty"`
	InvoiceHash      string                 `protobuf:"bytes,3,opt,name=invoice_hash,json=invoiceHash,proto3" json:"invoice_hash,omitempty"`
	MintHash         string                 `protobuf:"bytes,4,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	Quantity         int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OnChainInvoiceMessage) Reset() {
	*x = OnChainInvoiceMessage{}
	mi := &file_pkg_protocol_invoices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnChainInvoiceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainInvoiceMessage) ProtoMessage() {}

func (x *OnChainInvoiceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_invoices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainInvoiceMessage.ProtoReflect.Descriptor instead.
func (*OnChainInvoiceMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_invoices_proto_rawDescGZIP(), []int{0}
}

func (x *OnChainInvoiceMessage) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OnChainInvoiceMessage) GetSellOfferAddress() string {
	if x != nil {
		return x.SellOfferAddress
	}
	return ""
}

func (x *OnChainInvoiceMessage) GetInvoiceHash() string {
	if x != nil {
		return x.InvoiceHash
	}
	return ""
}

func (x *OnChainInvoiceMessage) GetMintHash() string {
	if x != nil {
		return x.MintHash
	}
	return ""
}

func (x *OnChainInvoiceMessage) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// This is what gets gossiped + stored in the gossip mempool + confirmed_transactions
type InvoiceMessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Payload       *InvoiceMessage        `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceMessageEnvelope) Reset() {
	*x = InvoiceMessageEnvelope{}
	mi := &file_pkg_protocol_invoices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceMessageEnvelope) ProtoMessage() {}

func (x *InvoiceMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_invoices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceMessageEnvelope.ProtoReflect.Descriptor instead.
func (*InvoiceMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_invoices_proto_rawDescGZIP(), []int{1}
}

func (x *InvoiceMessageEnvelope) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *InvoiceMessageEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *InvoiceMessageEnvelope) GetPayload() *InvoiceMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvoiceMessageEnvelope) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *InvoiceMessageEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type InvoicePayload struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PaymentAddress         string                 `protobuf:"bytes,1,opt,name=payment_address,json=paymentAddress,proto3" json:"payment_address,omitempty"`
	BuyOfferOffererAddress string                 `protobuf:"bytes,2,opt,name=buy_offer_offerer_address,json=buyOfferOffererAddress,proto3" json:"buy_offer_offerer_address,omitempty"`
	BuyOfferHash           string                 `protobuf:"bytes,3,opt,name=buy_offer_hash,json=buyOfferHash,proto3" json:"buy_offer_hash,omitempty"`
	BuyOfferMintHash       string                 `protobuf:"bytes,4,opt,name=buy_offer_mint_hash,json=buyOfferMintHash,proto3" json:"buy_offer_mint_hash,omitempty"`
	BuyOfferQuantity       int32                  `protobuf:"varint,5,opt,name=buy_offer_quantity,json=buyOfferQuantity,proto3" json:"buy_offer_quantity,omitempty"`
	BuyOfferPrice          int32                  `protobuf:"varint,6,opt,name=buy_offer_price,json=buyOfferPrice,proto3" json:"buy_offer_price,omitempty"`
	SellOfferAddress       string                 `protobuf:"bytes,7,opt,name=sell_offer_address,json=sellOfferAddress,proto3" json:"sell_offer_address,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InvoicePayload) Reset() {
	*x = InvoicePayload{}
	mi := &file_pkg_protocol_invoices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoicePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoicePayload) ProtoMessage() {}

func (x *InvoicePayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_invoices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoicePayload.ProtoReflect.Descriptor instead.
func (*InvoicePayload) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_invoices_proto_rawDescGZIP(), []int{2}
}

func (x *InvoicePayload) GetPaymentAddress() string {
	if x != nil {
		return x.PaymentAddress
	}
	return ""
}

func (x *InvoicePayload) GetBuyOfferOffererAddress() string {
	if x != nil {
		return x.BuyOfferOffererAddress
	}
	return ""
}

func (x *InvoicePayload) GetBuyOfferHash() string {
	if x != nil {
		return x.BuyOfferHash
	}
	return ""
}

func (x *InvoicePayload) GetBuyOfferMintHash() string {
	if x != nil {
		return x.BuyOfferMintHash
	}
	return ""
}

func (x *InvoicePayload) GetBuyOfferQuantity() int32 {
	if x != nil {
		return x.BuyOfferQuantity
	}
	return 0
}

func (x *InvoicePayload) GetBuyOfferPrice() int32 {
	if x != nil {
		return x.BuyOfferPrice
	}
	return 0
}

func (x *InvoicePayload) GetSellOfferAddress() string {
	if x != nil {
		return x.SellOfferAddress
	}
	return ""
}

type InvoiceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Payload       *InvoicePayload        `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceMessage) Reset() {
	*x = InvoiceMessage{}
	mi := &file_pkg_protocol_invoices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceMessage) ProtoMessage() {}

func (x *InvoiceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_invoices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceMessage.ProtoReflect.Descriptor instead.
func (*InvoiceMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_invoices_proto_rawDescGZIP(), []int{3}
}

func (x *InvoiceMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvoiceMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *InvoiceMessage) GetPayload() *InvoicePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvoiceMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_pkg_protocol_invoices_proto protoreflect.FileDescriptor

const file_pkg_protocol_invoices_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/protocol/invoices.proto\x12\rfractalengine\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\x15OnChainInvoiceMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12,\n" +
	"\x12sell_offer_address\x18\x02 \x01(\tR\x10sellOfferAddress\x12!\n" +
	"\finvoice_hash\x18\x03 \x01(\tR\vinvoiceHash\x12\x1b\n" +
	"\tmint_hash\x18\x04 \x01(\tR\bmintHash\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\"\xbc\x01\n" +
	"\x16InvoiceMessageEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x127\n" +
	"\apayload\x18\x03 \x01(\v2\x1d.fractalengine.InvoiceMessageR\apayload\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\"\xcd\x02\n" +
	"\x0eInvoicePayload\x12'\n" +
	"\x0fpayment_address\x18\x01 \x01(\tR\x0epaymentAddress\x129\n" +
	"\x19buy_offer_offerer_address\x18\x02 \x01(\tR\x16buyOfferOffererAddress\x12$\n" +
	"\x0ebuy_offer_hash\x18\x03 \x01(\tR\fbuyOfferHash\x12-\n" +
	"\x13buy_offer_mint_hash\x18\x04 \x01(\tR\x10buyOfferMintHash\x12,\n" +
	"\x12buy_offer_quantity\x18\x05 \x01(\x05R\x10buyOfferQuantity\x12&\n" +
	"\x0fbuy_offer_price\x18\x06 \x01(\x05R\rbuyOfferPrice\x12,\n" +
	"\x12sell_offer_address\x18\a \x01(\tR\x10sellOfferAddress\"\xa8\x01\n" +
	"\x0eInvoiceMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x127\n" +
	"\apayload\x18\x03 \x01(\v2\x1d.fractalengine.InvoicePayloadR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0eZ\fpkg/protocolb\x06proto3"

var (
	file_pkg_protocol_invoices_proto_rawDescOnce sync.Once
	file_pkg_protocol_invoices_proto_rawDescData []byte
)

func file_pkg_protocol_invoices_proto_rawDescGZIP() []byte {
	file_pkg_protocol_invoices_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_invoices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_invoices_proto_rawDesc), len(file_pkg_protocol_invoices_proto_rawDesc)))
	})
	return file_pkg_protocol_invoices_proto_rawDescData
}

var file_pkg_protocol_invoices_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_protocol_invoices_proto_goTypes = []any{
	(*OnChainInvoiceMessage)(nil),  // 0: fractalengine.OnChainInvoiceMessage
	(*InvoiceMessageEnvelope)(nil), // 1: fractalengine.InvoiceMessageEnvelope
	(*InvoicePayload)(nil),         // 2: fractalengine.InvoicePayload
	(*InvoiceMessage)(nil),         // 3: fractalengine.InvoiceMessage
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_pkg_protocol_invoices_proto_depIdxs = []int32{
	3, // 0: fractalengine.InvoiceMessageEnvelope.payload:type_name -> fractalengine.InvoiceMessage
	2, // 1: fractalengine.InvoiceMessage.payload:type_name -> fractalengine.InvoicePayload
	4, // 2: fractalengine.InvoiceMessage.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_protocol_invoices_proto_init() }
func file_pkg_protocol_invoices_proto_init() {
	if File_pkg_protocol_invoices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_invoices_proto_rawDesc), len(file_pkg_protocol_invoices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_invoices_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_invoices_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_invoices_proto_msgTypes,
	}.Build()
	File_pkg_protocol_invoices_proto = out.File
	file_pkg_protocol_invoices_proto_goTypes = nil
	file_pkg_protocol_invoices_proto_depIdxs = nil
}
