// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0--rc2
// source: pkg/protocol/mint.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MintMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FractionCount   int32                  `protobuf:"varint,4,opt,name=fraction_count,json=fractionCount,proto3" json:"fraction_count,omitempty"`
	Tags            string                 `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	TransactionHash string                 `protobuf:"bytes,6,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	Metadata        *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Hash            string                 `protobuf:"bytes,8,opt,name=hash,proto3" json:"hash,omitempty"`
	Requirements    *structpb.Struct       `protobuf:"bytes,9,opt,name=requirements,proto3" json:"requirements,omitempty"`
	Resellable      bool                   `protobuf:"varint,10,opt,name=resellable,proto3" json:"resellable,omitempty"`
	LockupOptions   *structpb.Struct       `protobuf:"bytes,11,opt,name=lockup_options,json=lockupOptions,proto3" json:"lockup_options,omitempty"`
	Gossiped        bool                   `protobuf:"varint,12,opt,name=gossiped,proto3" json:"gossiped,omitempty"`
	Verified        bool                   `protobuf:"varint,13,opt,name=verified,proto3" json:"verified,omitempty"`
	FeedUrl         string                 `protobuf:"bytes,14,opt,name=feed_url,json=feedUrl,proto3" json:"feed_url,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MintMessage) Reset() {
	*x = MintMessage{}
	mi := &file_pkg_protocol_mint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintMessage) ProtoMessage() {}

func (x *MintMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_mint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintMessage.ProtoReflect.Descriptor instead.
func (*MintMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_mint_proto_rawDescGZIP(), []int{0}
}

func (x *MintMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MintMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MintMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MintMessage) GetFractionCount() int32 {
	if x != nil {
		return x.FractionCount
	}
	return 0
}

func (x *MintMessage) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *MintMessage) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *MintMessage) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MintMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *MintMessage) GetRequirements() *structpb.Struct {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *MintMessage) GetResellable() bool {
	if x != nil {
		return x.Resellable
	}
	return false
}

func (x *MintMessage) GetLockupOptions() *structpb.Struct {
	if x != nil {
		return x.LockupOptions
	}
	return nil
}

func (x *MintMessage) GetGossiped() bool {
	if x != nil {
		return x.Gossiped
	}
	return false
}

func (x *MintMessage) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *MintMessage) GetFeedUrl() string {
	if x != nil {
		return x.FeedUrl
	}
	return ""
}

func (x *MintMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_pkg_protocol_mint_proto protoreflect.FileDescriptor

const file_pkg_protocol_mint_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/protocol/mint.proto\x12\rfractalengine\x1a\x1cgoogle/protobuf/struct.proto\"\x93\x04\n" +
	"\vMintMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0efraction_count\x18\x04 \x01(\x05R\rfractionCount\x12\x12\n" +
	"\x04tags\x18\x05 \x01(\tR\x04tags\x12)\n" +
	"\x10transaction_hash\x18\x06 \x01(\tR\x0ftransactionHash\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x12\n" +
	"\x04hash\x18\b \x01(\tR\x04hash\x12;\n" +
	"\frequirements\x18\t \x01(\v2\x17.google.protobuf.StructR\frequirements\x12\x1e\n" +
	"\n" +
	"resellable\x18\n" +
	" \x01(\bR\n" +
	"resellable\x12>\n" +
	"\x0elockup_options\x18\v \x01(\v2\x17.google.protobuf.StructR\rlockupOptions\x12\x1a\n" +
	"\bgossiped\x18\f \x01(\bR\bgossiped\x12\x1a\n" +
	"\bverified\x18\r \x01(\bR\bverified\x12\x19\n" +
	"\bfeed_url\x18\x0e \x01(\tR\afeedUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAtB\x0eZ\fpkg/protocolb\x06proto3"

var (
	file_pkg_protocol_mint_proto_rawDescOnce sync.Once
	file_pkg_protocol_mint_proto_rawDescData []byte
)

func file_pkg_protocol_mint_proto_rawDescGZIP() []byte {
	file_pkg_protocol_mint_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_mint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_mint_proto_rawDesc), len(file_pkg_protocol_mint_proto_rawDesc)))
	})
	return file_pkg_protocol_mint_proto_rawDescData
}

var file_pkg_protocol_mint_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_protocol_mint_proto_goTypes = []any{
	(*MintMessage)(nil),     // 0: fractalengine.MintMessage
	(*structpb.Struct)(nil), // 1: google.protobuf.Struct
}
var file_pkg_protocol_mint_proto_depIdxs = []int32{
	1, // 0: fractalengine.MintMessage.metadata:type_name -> google.protobuf.Struct
	1, // 1: fractalengine.MintMessage.requirements:type_name -> google.protobuf.Struct
	1, // 2: fractalengine.MintMessage.lockup_options:type_name -> google.protobuf.Struct
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_protocol_mint_proto_init() }
func file_pkg_protocol_mint_proto_init() {
	if File_pkg_protocol_mint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_mint_proto_rawDesc), len(file_pkg_protocol_mint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_mint_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_mint_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_mint_proto_msgTypes,
	}.Build()
	File_pkg_protocol_mint_proto = out.File
	file_pkg_protocol_mint_proto_goTypes = nil
	file_pkg_protocol_mint_proto_depIdxs = nil
}
