// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: pkg/protocol/mint.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is what gets written to the OP_RETURN on the L1
type OnChainMintMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnChainMintMessage) Reset() {
	*x = OnChainMintMessage{}
	mi := &file_pkg_protocol_mint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnChainMintMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainMintMessage) ProtoMessage() {}

func (x *OnChainMintMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_mint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainMintMessage.ProtoReflect.Descriptor instead.
func (*OnChainMintMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_mint_proto_rawDescGZIP(), []int{0}
}

func (x *OnChainMintMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// This is what gets gossiped + stored in the gossip mempool + confirmed_transactions
type MintMessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Payload       *MintMessage           `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintMessageEnvelope) Reset() {
	*x = MintMessageEnvelope{}
	mi := &file_pkg_protocol_mint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintMessageEnvelope) ProtoMessage() {}

func (x *MintMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_mint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintMessageEnvelope.ProtoReflect.Descriptor instead.
func (*MintMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_mint_proto_rawDescGZIP(), []int{1}
}

func (x *MintMessageEnvelope) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MintMessageEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MintMessageEnvelope) GetPayload() *MintMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MintMessageEnvelope) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *MintMessageEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type AssetManager struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetManager) Reset() {
	*x = AssetManager{}
	mi := &file_pkg_protocol_mint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetManager) ProtoMessage() {}

func (x *AssetManager) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_mint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetManager.ProtoReflect.Descriptor instead.
func (*AssetManager) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_mint_proto_rawDescGZIP(), []int{2}
}

func (x *AssetManager) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssetManager) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AssetManager) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Payload of a mint
type MintMessage struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Title                    string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description              string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	FractionCount            int32                  `protobuf:"varint,3,opt,name=fraction_count,json=fractionCount,proto3" json:"fraction_count,omitempty"`
	Tags                     []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	TransactionHash          string                 `protobuf:"bytes,5,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	Metadata                 *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Hash                     string                 `protobuf:"bytes,7,opt,name=hash,proto3" json:"hash,omitempty"`
	Requirements             *structpb.Struct       `protobuf:"bytes,8,opt,name=requirements,proto3" json:"requirements,omitempty"`
	LockupOptions            *structpb.Struct       `protobuf:"bytes,9,opt,name=lockup_options,json=lockupOptions,proto3" json:"lockup_options,omitempty"`
	FeedUrl                  string                 `protobuf:"bytes,10,opt,name=feed_url,json=feedUrl,proto3" json:"feed_url,omitempty"`
	CreatedAt                *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	BlockHeight              int32                  `protobuf:"varint,12,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	ContractOfSale           string                 `protobuf:"bytes,13,opt,name=contract_of_sale,json=contractOfSale,proto3" json:"contract_of_sale,omitempty"`
	OwnerAddress             string                 `protobuf:"bytes,14,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	SignatureRequirementType string                 `protobuf:"bytes,15,opt,name=signature_requirement_type,json=signatureRequirementType,proto3" json:"signature_requirement_type,omitempty"`
	AssetManagers            []*AssetManager        `protobuf:"bytes,16,rep,name=asset_managers,json=assetManagers,proto3" json:"asset_managers,omitempty"`
	MinSignatures            int32                  `protobuf:"varint,17,opt,name=min_signatures,json=minSignatures,proto3" json:"min_signatures,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MintMessage) Reset() {
	*x = MintMessage{}
	mi := &file_pkg_protocol_mint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintMessage) ProtoMessage() {}

func (x *MintMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_mint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintMessage.ProtoReflect.Descriptor instead.
func (*MintMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_mint_proto_rawDescGZIP(), []int{3}
}

func (x *MintMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MintMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MintMessage) GetFractionCount() int32 {
	if x != nil {
		return x.FractionCount
	}
	return 0
}

func (x *MintMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MintMessage) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *MintMessage) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MintMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *MintMessage) GetRequirements() *structpb.Struct {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *MintMessage) GetLockupOptions() *structpb.Struct {
	if x != nil {
		return x.LockupOptions
	}
	return nil
}

func (x *MintMessage) GetFeedUrl() string {
	if x != nil {
		return x.FeedUrl
	}
	return ""
}

func (x *MintMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MintMessage) GetBlockHeight() int32 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *MintMessage) GetContractOfSale() string {
	if x != nil {
		return x.ContractOfSale
	}
	return ""
}

func (x *MintMessage) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *MintMessage) GetSignatureRequirementType() string {
	if x != nil {
		return x.SignatureRequirementType
	}
	return ""
}

func (x *MintMessage) GetAssetManagers() []*AssetManager {
	if x != nil {
		return x.AssetManagers
	}
	return nil
}

func (x *MintMessage) GetMinSignatures() int32 {
	if x != nil {
		return x.MinSignatures
	}
	return 0
}

var File_pkg_protocol_mint_proto protoreflect.FileDescriptor

const file_pkg_protocol_mint_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/protocol/mint.proto\x12\rfractalengine\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n" +
	"\x12OnChainMintMessage\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\xb6\x01\n" +
	"\x13MintMessageEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x124\n" +
	"\apayload\x18\x03 \x01(\v2\x1a.fractalengine.MintMessageR\apayload\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\"S\n" +
	"\fAssetManager\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\xe2\x05\n" +
	"\vMintMessage\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12%\n" +
	"\x0efraction_count\x18\x03 \x01(\x05R\rfractionCount\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12)\n" +
	"\x10transaction_hash\x18\x05 \x01(\tR\x0ftransactionHash\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x12\n" +
	"\x04hash\x18\a \x01(\tR\x04hash\x12;\n" +
	"\frequirements\x18\b \x01(\v2\x17.google.protobuf.StructR\frequirements\x12>\n" +
	"\x0elockup_options\x18\t \x01(\v2\x17.google.protobuf.StructR\rlockupOptions\x12\x19\n" +
	"\bfeed_url\x18\n" +
	" \x01(\tR\afeedUrl\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\fblock_height\x18\f \x01(\x05R\vblockHeight\x12(\n" +
	"\x10contract_of_sale\x18\r \x01(\tR\x0econtractOfSale\x12#\n" +
	"\rowner_address\x18\x0e \x01(\tR\fownerAddress\x12<\n" +
	"\x1asignature_requirement_type\x18\x0f \x01(\tR\x18signatureRequirementType\x12B\n" +
	"\x0easset_managers\x18\x10 \x03(\v2\x1b.fractalengine.AssetManagerR\rassetManagers\x12%\n" +
	"\x0emin_signatures\x18\x11 \x01(\x05R\rminSignaturesB\x0eZ\fpkg/protocolb\x06proto3"

var (
	file_pkg_protocol_mint_proto_rawDescOnce sync.Once
	file_pkg_protocol_mint_proto_rawDescData []byte
)

func file_pkg_protocol_mint_proto_rawDescGZIP() []byte {
	file_pkg_protocol_mint_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_mint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_mint_proto_rawDesc), len(file_pkg_protocol_mint_proto_rawDesc)))
	})
	return file_pkg_protocol_mint_proto_rawDescData
}

var file_pkg_protocol_mint_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_protocol_mint_proto_goTypes = []any{
	(*OnChainMintMessage)(nil),    // 0: fractalengine.OnChainMintMessage
	(*MintMessageEnvelope)(nil),   // 1: fractalengine.MintMessageEnvelope
	(*AssetManager)(nil),          // 2: fractalengine.AssetManager
	(*MintMessage)(nil),           // 3: fractalengine.MintMessage
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_pkg_protocol_mint_proto_depIdxs = []int32{
	3, // 0: fractalengine.MintMessageEnvelope.payload:type_name -> fractalengine.MintMessage
	4, // 1: fractalengine.MintMessage.metadata:type_name -> google.protobuf.Struct
	4, // 2: fractalengine.MintMessage.requirements:type_name -> google.protobuf.Struct
	4, // 3: fractalengine.MintMessage.lockup_options:type_name -> google.protobuf.Struct
	5, // 4: fractalengine.MintMessage.created_at:type_name -> google.protobuf.Timestamp
	2, // 5: fractalengine.MintMessage.asset_managers:type_name -> fractalengine.AssetManager
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_protocol_mint_proto_init() }
func file_pkg_protocol_mint_proto_init() {
	if File_pkg_protocol_mint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_mint_proto_rawDesc), len(file_pkg_protocol_mint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_mint_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_mint_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_mint_proto_msgTypes,
	}.Build()
	File_pkg_protocol_mint_proto = out.File
	file_pkg_protocol_mint_proto_goTypes = nil
	file_pkg_protocol_mint_proto_depIdxs = nil
}
