// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0--rc2
// source: pkg/protocol/offers.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuyOfferMessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Payload       *BuyOfferMessage       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyOfferMessageEnvelope) Reset() {
	*x = BuyOfferMessageEnvelope{}
	mi := &file_pkg_protocol_offers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyOfferMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyOfferMessageEnvelope) ProtoMessage() {}

func (x *BuyOfferMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_offers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyOfferMessageEnvelope.ProtoReflect.Descriptor instead.
func (*BuyOfferMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_offers_proto_rawDescGZIP(), []int{0}
}

func (x *BuyOfferMessageEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BuyOfferMessageEnvelope) GetPayload() *BuyOfferMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BuyOfferMessageEnvelope) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *BuyOfferMessageEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type SellOfferMessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Payload       *SellOfferMessage      `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellOfferMessageEnvelope) Reset() {
	*x = SellOfferMessageEnvelope{}
	mi := &file_pkg_protocol_offers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellOfferMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellOfferMessageEnvelope) ProtoMessage() {}

func (x *SellOfferMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_offers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellOfferMessageEnvelope.ProtoReflect.Descriptor instead.
func (*SellOfferMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_offers_proto_rawDescGZIP(), []int{1}
}

func (x *SellOfferMessageEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SellOfferMessageEnvelope) GetPayload() *SellOfferMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SellOfferMessageEnvelope) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SellOfferMessageEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type BuyOfferMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OffererAddress string                 `protobuf:"bytes,2,opt,name=offerer_address,json=offererAddress,proto3" json:"offerer_address,omitempty"`
	SellerAddress  string                 `protobuf:"bytes,3,opt,name=seller_address,json=sellerAddress,proto3" json:"seller_address,omitempty"`
	Hash           string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	MintHash       string                 `protobuf:"bytes,5,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	Quantity       int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price          int32                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuyOfferMessage) Reset() {
	*x = BuyOfferMessage{}
	mi := &file_pkg_protocol_offers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyOfferMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyOfferMessage) ProtoMessage() {}

func (x *BuyOfferMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_offers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyOfferMessage.ProtoReflect.Descriptor instead.
func (*BuyOfferMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_offers_proto_rawDescGZIP(), []int{2}
}

func (x *BuyOfferMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuyOfferMessage) GetOffererAddress() string {
	if x != nil {
		return x.OffererAddress
	}
	return ""
}

func (x *BuyOfferMessage) GetSellerAddress() string {
	if x != nil {
		return x.SellerAddress
	}
	return ""
}

func (x *BuyOfferMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BuyOfferMessage) GetMintHash() string {
	if x != nil {
		return x.MintHash
	}
	return ""
}

func (x *BuyOfferMessage) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BuyOfferMessage) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BuyOfferMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SellOfferMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OffererAddress string                 `protobuf:"bytes,2,opt,name=offerer_address,json=offererAddress,proto3" json:"offerer_address,omitempty"`
	Hash           string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	MintHash       string                 `protobuf:"bytes,4,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	Quantity       int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price          int32                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SellOfferMessage) Reset() {
	*x = SellOfferMessage{}
	mi := &file_pkg_protocol_offers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellOfferMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellOfferMessage) ProtoMessage() {}

func (x *SellOfferMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_offers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellOfferMessage.ProtoReflect.Descriptor instead.
func (*SellOfferMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_offers_proto_rawDescGZIP(), []int{3}
}

func (x *SellOfferMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SellOfferMessage) GetOffererAddress() string {
	if x != nil {
		return x.OffererAddress
	}
	return ""
}

func (x *SellOfferMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SellOfferMessage) GetMintHash() string {
	if x != nil {
		return x.MintHash
	}
	return ""
}

func (x *SellOfferMessage) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SellOfferMessage) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SellOfferMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DeleteBuyOfferMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuyOfferMessage) Reset() {
	*x = DeleteBuyOfferMessage{}
	mi := &file_pkg_protocol_offers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuyOfferMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuyOfferMessage) ProtoMessage() {}

func (x *DeleteBuyOfferMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_offers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuyOfferMessage.ProtoReflect.Descriptor instead.
func (*DeleteBuyOfferMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_offers_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBuyOfferMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type DeleteBuyOfferMessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Payload       *DeleteBuyOfferMessage `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuyOfferMessageEnvelope) Reset() {
	*x = DeleteBuyOfferMessageEnvelope{}
	mi := &file_pkg_protocol_offers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuyOfferMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuyOfferMessageEnvelope) ProtoMessage() {}

func (x *DeleteBuyOfferMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_offers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuyOfferMessageEnvelope.ProtoReflect.Descriptor instead.
func (*DeleteBuyOfferMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_offers_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBuyOfferMessageEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DeleteBuyOfferMessageEnvelope) GetPayload() *DeleteBuyOfferMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeleteBuyOfferMessageEnvelope) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DeleteBuyOfferMessageEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type DeleteSellOfferMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSellOfferMessage) Reset() {
	*x = DeleteSellOfferMessage{}
	mi := &file_pkg_protocol_offers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSellOfferMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellOfferMessage) ProtoMessage() {}

func (x *DeleteSellOfferMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_offers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSellOfferMessage.ProtoReflect.Descriptor instead.
func (*DeleteSellOfferMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_offers_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSellOfferMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type DeleteSellOfferMessageEnvelope struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Version       int32                   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Payload       *DeleteSellOfferMessage `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                  `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                  `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSellOfferMessageEnvelope) Reset() {
	*x = DeleteSellOfferMessageEnvelope{}
	mi := &file_pkg_protocol_offers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSellOfferMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellOfferMessageEnvelope) ProtoMessage() {}

func (x *DeleteSellOfferMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_offers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSellOfferMessageEnvelope.ProtoReflect.Descriptor instead.
func (*DeleteSellOfferMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_offers_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSellOfferMessageEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DeleteSellOfferMessageEnvelope) GetPayload() *DeleteSellOfferMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeleteSellOfferMessageEnvelope) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DeleteSellOfferMessageEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_pkg_protocol_offers_proto protoreflect.FileDescriptor

const file_pkg_protocol_offers_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/protocol/offers.proto\x12\rfractalengine\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\x17BuyOfferMessageEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x128\n" +
	"\apayload\x18\x02 \x01(\v2\x1e.fractalengine.BuyOfferMessageR\apayload\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"\xac\x01\n" +
	"\x18SellOfferMessageEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x129\n" +
	"\apayload\x18\x02 \x01(\v2\x1f.fractalengine.SellOfferMessageR\apayload\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"\x8f\x02\n" +
	"\x0fBuyOfferMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fofferer_address\x18\x02 \x01(\tR\x0eoffererAddress\x12%\n" +
	"\x0eseller_address\x18\x03 \x01(\tR\rsellerAddress\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x1b\n" +
	"\tmint_hash\x18\x05 \x01(\tR\bmintHash\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\a \x01(\x05R\x05price\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe9\x01\n" +
	"\x10SellOfferMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fofferer_address\x18\x02 \x01(\tR\x0eoffererAddress\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x1b\n" +
	"\tmint_hash\x18\x04 \x01(\tR\bmintHash\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x05R\x05price\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"+\n" +
	"\x15DeleteBuyOfferMessage\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\xb6\x01\n" +
	"\x1dDeleteBuyOfferMessageEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12>\n" +
	"\apayload\x18\x02 \x01(\v2$.fractalengine.DeleteBuyOfferMessageR\apayload\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\",\n" +
	"\x16DeleteSellOfferMessage\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\xb8\x01\n" +
	"\x1eDeleteSellOfferMessageEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12?\n" +
	"\apayload\x18\x02 \x01(\v2%.fractalengine.DeleteSellOfferMessageR\apayload\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignatureB\x0eZ\fpkg/protocolb\x06proto3"

var (
	file_pkg_protocol_offers_proto_rawDescOnce sync.Once
	file_pkg_protocol_offers_proto_rawDescData []byte
)

func file_pkg_protocol_offers_proto_rawDescGZIP() []byte {
	file_pkg_protocol_offers_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_offers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_offers_proto_rawDesc), len(file_pkg_protocol_offers_proto_rawDesc)))
	})
	return file_pkg_protocol_offers_proto_rawDescData
}

var file_pkg_protocol_offers_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_protocol_offers_proto_goTypes = []any{
	(*BuyOfferMessageEnvelope)(nil),        // 0: fractalengine.BuyOfferMessageEnvelope
	(*SellOfferMessageEnvelope)(nil),       // 1: fractalengine.SellOfferMessageEnvelope
	(*BuyOfferMessage)(nil),                // 2: fractalengine.BuyOfferMessage
	(*SellOfferMessage)(nil),               // 3: fractalengine.SellOfferMessage
	(*DeleteBuyOfferMessage)(nil),          // 4: fractalengine.DeleteBuyOfferMessage
	(*DeleteBuyOfferMessageEnvelope)(nil),  // 5: fractalengine.DeleteBuyOfferMessageEnvelope
	(*DeleteSellOfferMessage)(nil),         // 6: fractalengine.DeleteSellOfferMessage
	(*DeleteSellOfferMessageEnvelope)(nil), // 7: fractalengine.DeleteSellOfferMessageEnvelope
	(*timestamppb.Timestamp)(nil),          // 8: google.protobuf.Timestamp
}
var file_pkg_protocol_offers_proto_depIdxs = []int32{
	2, // 0: fractalengine.BuyOfferMessageEnvelope.payload:type_name -> fractalengine.BuyOfferMessage
	3, // 1: fractalengine.SellOfferMessageEnvelope.payload:type_name -> fractalengine.SellOfferMessage
	8, // 2: fractalengine.BuyOfferMessage.created_at:type_name -> google.protobuf.Timestamp
	8, // 3: fractalengine.SellOfferMessage.created_at:type_name -> google.protobuf.Timestamp
	4, // 4: fractalengine.DeleteBuyOfferMessageEnvelope.payload:type_name -> fractalengine.DeleteBuyOfferMessage
	6, // 5: fractalengine.DeleteSellOfferMessageEnvelope.payload:type_name -> fractalengine.DeleteSellOfferMessage
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_protocol_offers_proto_init() }
func file_pkg_protocol_offers_proto_init() {
	if File_pkg_protocol_offers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_offers_proto_rawDesc), len(file_pkg_protocol_offers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_offers_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_offers_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_offers_proto_msgTypes,
	}.Build()
	File_pkg_protocol_offers_proto = out.File
	file_pkg_protocol_offers_proto_goTypes = nil
	file_pkg_protocol_offers_proto_depIdxs = nil
}
