// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0--rc2
// source: pkg/protocol/offers.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuyOfferMessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Payload       *BuyOfferMessage       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyOfferMessageEnvelope) Reset() {
	*x = BuyOfferMessageEnvelope{}
	mi := &file_pkg_protocol_offers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyOfferMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyOfferMessageEnvelope) ProtoMessage() {}

func (x *BuyOfferMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_offers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyOfferMessageEnvelope.ProtoReflect.Descriptor instead.
func (*BuyOfferMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_offers_proto_rawDescGZIP(), []int{0}
}

func (x *BuyOfferMessageEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BuyOfferMessageEnvelope) GetPayload() *BuyOfferMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SellOfferMessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Payload       *SellOfferMessage      `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellOfferMessageEnvelope) Reset() {
	*x = SellOfferMessageEnvelope{}
	mi := &file_pkg_protocol_offers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellOfferMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellOfferMessageEnvelope) ProtoMessage() {}

func (x *SellOfferMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_offers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellOfferMessageEnvelope.ProtoReflect.Descriptor instead.
func (*SellOfferMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_offers_proto_rawDescGZIP(), []int{1}
}

func (x *SellOfferMessageEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SellOfferMessageEnvelope) GetPayload() *SellOfferMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BuyOfferMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OffererAddress string                 `protobuf:"bytes,2,opt,name=offerer_address,json=offererAddress,proto3" json:"offerer_address,omitempty"`
	SellerAddress  string                 `protobuf:"bytes,3,opt,name=seller_address,json=sellerAddress,proto3" json:"seller_address,omitempty"`
	Hash           string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	MintHash       string                 `protobuf:"bytes,5,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	Quantity       int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price          int32                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuyOfferMessage) Reset() {
	*x = BuyOfferMessage{}
	mi := &file_pkg_protocol_offers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyOfferMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyOfferMessage) ProtoMessage() {}

func (x *BuyOfferMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_offers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyOfferMessage.ProtoReflect.Descriptor instead.
func (*BuyOfferMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_offers_proto_rawDescGZIP(), []int{2}
}

func (x *BuyOfferMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuyOfferMessage) GetOffererAddress() string {
	if x != nil {
		return x.OffererAddress
	}
	return ""
}

func (x *BuyOfferMessage) GetSellerAddress() string {
	if x != nil {
		return x.SellerAddress
	}
	return ""
}

func (x *BuyOfferMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BuyOfferMessage) GetMintHash() string {
	if x != nil {
		return x.MintHash
	}
	return ""
}

func (x *BuyOfferMessage) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BuyOfferMessage) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BuyOfferMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SellOfferMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OffererAddress string                 `protobuf:"bytes,2,opt,name=offerer_address,json=offererAddress,proto3" json:"offerer_address,omitempty"`
	Hash           string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	MintHash       string                 `protobuf:"bytes,4,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	Quantity       int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price          int32                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SellOfferMessage) Reset() {
	*x = SellOfferMessage{}
	mi := &file_pkg_protocol_offers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellOfferMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellOfferMessage) ProtoMessage() {}

func (x *SellOfferMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_offers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellOfferMessage.ProtoReflect.Descriptor instead.
func (*SellOfferMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_offers_proto_rawDescGZIP(), []int{3}
}

func (x *SellOfferMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SellOfferMessage) GetOffererAddress() string {
	if x != nil {
		return x.OffererAddress
	}
	return ""
}

func (x *SellOfferMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SellOfferMessage) GetMintHash() string {
	if x != nil {
		return x.MintHash
	}
	return ""
}

func (x *SellOfferMessage) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SellOfferMessage) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SellOfferMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_pkg_protocol_offers_proto protoreflect.FileDescriptor

const file_pkg_protocol_offers_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/protocol/offers.proto\x12\rfractalengine\x1a\x1fgoogle/protobuf/timestamp.proto\"m\n" +
	"\x17BuyOfferMessageEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x128\n" +
	"\apayload\x18\x02 \x01(\v2\x1e.fractalengine.BuyOfferMessageR\apayload\"o\n" +
	"\x18SellOfferMessageEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x129\n" +
	"\apayload\x18\x02 \x01(\v2\x1f.fractalengine.SellOfferMessageR\apayload\"\x8f\x02\n" +
	"\x0fBuyOfferMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fofferer_address\x18\x02 \x01(\tR\x0eoffererAddress\x12%\n" +
	"\x0eseller_address\x18\x03 \x01(\tR\rsellerAddress\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x1b\n" +
	"\tmint_hash\x18\x05 \x01(\tR\bmintHash\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\a \x01(\x05R\x05price\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe9\x01\n" +
	"\x10SellOfferMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fofferer_address\x18\x02 \x01(\tR\x0eoffererAddress\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x1b\n" +
	"\tmint_hash\x18\x04 \x01(\tR\bmintHash\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x05R\x05price\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0eZ\fpkg/protocolb\x06proto3"

var (
	file_pkg_protocol_offers_proto_rawDescOnce sync.Once
	file_pkg_protocol_offers_proto_rawDescData []byte
)

func file_pkg_protocol_offers_proto_rawDescGZIP() []byte {
	file_pkg_protocol_offers_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_offers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_offers_proto_rawDesc), len(file_pkg_protocol_offers_proto_rawDesc)))
	})
	return file_pkg_protocol_offers_proto_rawDescData
}

var file_pkg_protocol_offers_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_protocol_offers_proto_goTypes = []any{
	(*BuyOfferMessageEnvelope)(nil),  // 0: fractalengine.BuyOfferMessageEnvelope
	(*SellOfferMessageEnvelope)(nil), // 1: fractalengine.SellOfferMessageEnvelope
	(*BuyOfferMessage)(nil),          // 2: fractalengine.BuyOfferMessage
	(*SellOfferMessage)(nil),         // 3: fractalengine.SellOfferMessage
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
}
var file_pkg_protocol_offers_proto_depIdxs = []int32{
	2, // 0: fractalengine.BuyOfferMessageEnvelope.payload:type_name -> fractalengine.BuyOfferMessage
	3, // 1: fractalengine.SellOfferMessageEnvelope.payload:type_name -> fractalengine.SellOfferMessage
	4, // 2: fractalengine.BuyOfferMessage.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: fractalengine.SellOfferMessage.created_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_protocol_offers_proto_init() }
func file_pkg_protocol_offers_proto_init() {
	if File_pkg_protocol_offers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_offers_proto_rawDesc), len(file_pkg_protocol_offers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_offers_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_offers_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_offers_proto_msgTypes,
	}.Build()
	File_pkg_protocol_offers_proto = out.File
	file_pkg_protocol_offers_proto_goTypes = nil
	file_pkg_protocol_offers_proto_depIdxs = nil
}
