// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0--rc2
// source: pkg/protocol/payment.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is what gets written to the OP_RETURN on the L1
type OnChainPaymentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnChainPaymentMessage) Reset() {
	*x = OnChainPaymentMessage{}
	mi := &file_pkg_protocol_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnChainPaymentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainPaymentMessage) ProtoMessage() {}

func (x *OnChainPaymentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainPaymentMessage.ProtoReflect.Descriptor instead.
func (*OnChainPaymentMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_payment_proto_rawDescGZIP(), []int{0}
}

func (x *OnChainPaymentMessage) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OnChainPaymentMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// This is what gets gossiped + stored in the gossip mempool + confirmed_transactions
type PaymentMessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Payload       *PaymentMessage        `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMessageEnvelope) Reset() {
	*x = PaymentMessageEnvelope{}
	mi := &file_pkg_protocol_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMessageEnvelope) ProtoMessage() {}

func (x *PaymentMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMessageEnvelope.ProtoReflect.Descriptor instead.
func (*PaymentMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentMessageEnvelope) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PaymentMessageEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PaymentMessageEnvelope) GetPayload() *PaymentMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Payload of an invoice
type PaymentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceHash   string                 `protobuf:"bytes,1,opt,name=invoice_hash,json=invoiceHash,proto3" json:"invoice_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMessage) Reset() {
	*x = PaymentMessage{}
	mi := &file_pkg_protocol_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMessage) ProtoMessage() {}

func (x *PaymentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMessage.ProtoReflect.Descriptor instead.
func (*PaymentMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentMessage) GetInvoiceHash() string {
	if x != nil {
		return x.InvoiceHash
	}
	return ""
}

var File_pkg_protocol_payment_proto protoreflect.FileDescriptor

const file_pkg_protocol_payment_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/protocol/payment.proto\x12\rfractalengine\"E\n" +
	"\x15OnChainPaymentMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"\x7f\n" +
	"\x16PaymentMessageEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x127\n" +
	"\apayload\x18\x03 \x01(\v2\x1d.fractalengine.PaymentMessageR\apayload\"3\n" +
	"\x0ePaymentMessage\x12!\n" +
	"\finvoice_hash\x18\x01 \x01(\tR\vinvoiceHashB\x0eZ\fpkg/protocolb\x06proto3"

var (
	file_pkg_protocol_payment_proto_rawDescOnce sync.Once
	file_pkg_protocol_payment_proto_rawDescData []byte
)

func file_pkg_protocol_payment_proto_rawDescGZIP() []byte {
	file_pkg_protocol_payment_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_payment_proto_rawDesc), len(file_pkg_protocol_payment_proto_rawDesc)))
	})
	return file_pkg_protocol_payment_proto_rawDescData
}

var file_pkg_protocol_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_protocol_payment_proto_goTypes = []any{
	(*OnChainPaymentMessage)(nil),  // 0: fractalengine.OnChainPaymentMessage
	(*PaymentMessageEnvelope)(nil), // 1: fractalengine.PaymentMessageEnvelope
	(*PaymentMessage)(nil),         // 2: fractalengine.PaymentMessage
}
var file_pkg_protocol_payment_proto_depIdxs = []int32{
	2, // 0: fractalengine.PaymentMessageEnvelope.payload:type_name -> fractalengine.PaymentMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_protocol_payment_proto_init() }
func file_pkg_protocol_payment_proto_init() {
	if File_pkg_protocol_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_payment_proto_rawDesc), len(file_pkg_protocol_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_payment_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_payment_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_payment_proto_msgTypes,
	}.Build()
	File_pkg_protocol_payment_proto = out.File
	file_pkg_protocol_payment_proto_goTypes = nil
	file_pkg_protocol_payment_proto_depIdxs = nil
}
