// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: pkg/protocol/sell_offers.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SellOfferMessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Payload       *SellOfferMessage      `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellOfferMessageEnvelope) Reset() {
	*x = SellOfferMessageEnvelope{}
	mi := &file_pkg_protocol_sell_offers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellOfferMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellOfferMessageEnvelope) ProtoMessage() {}

func (x *SellOfferMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_sell_offers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellOfferMessageEnvelope.ProtoReflect.Descriptor instead.
func (*SellOfferMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_sell_offers_proto_rawDescGZIP(), []int{0}
}

func (x *SellOfferMessageEnvelope) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SellOfferMessageEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SellOfferMessageEnvelope) GetPayload() *SellOfferMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SellOfferMessageEnvelope) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SellOfferMessageEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type SellOfferMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Payload       *SellOfferPayload      `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellOfferMessage) Reset() {
	*x = SellOfferMessage{}
	mi := &file_pkg_protocol_sell_offers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellOfferMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellOfferMessage) ProtoMessage() {}

func (x *SellOfferMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_sell_offers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellOfferMessage.ProtoReflect.Descriptor instead.
func (*SellOfferMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_sell_offers_proto_rawDescGZIP(), []int{1}
}

func (x *SellOfferMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SellOfferMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SellOfferMessage) GetPayload() *SellOfferPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SellOfferMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SellOfferPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OffererAddress string                 `protobuf:"bytes,1,opt,name=offerer_address,json=offererAddress,proto3" json:"offerer_address,omitempty"`
	MintHash       string                 `protobuf:"bytes,2,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	Quantity       int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price          int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SellOfferPayload) Reset() {
	*x = SellOfferPayload{}
	mi := &file_pkg_protocol_sell_offers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellOfferPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellOfferPayload) ProtoMessage() {}

func (x *SellOfferPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_sell_offers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellOfferPayload.ProtoReflect.Descriptor instead.
func (*SellOfferPayload) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_sell_offers_proto_rawDescGZIP(), []int{2}
}

func (x *SellOfferPayload) GetOffererAddress() string {
	if x != nil {
		return x.OffererAddress
	}
	return ""
}

func (x *SellOfferPayload) GetMintHash() string {
	if x != nil {
		return x.MintHash
	}
	return ""
}

func (x *SellOfferPayload) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SellOfferPayload) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type DeleteSellOfferMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSellOfferMessage) Reset() {
	*x = DeleteSellOfferMessage{}
	mi := &file_pkg_protocol_sell_offers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSellOfferMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellOfferMessage) ProtoMessage() {}

func (x *DeleteSellOfferMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_sell_offers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSellOfferMessage.ProtoReflect.Descriptor instead.
func (*DeleteSellOfferMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_sell_offers_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSellOfferMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type DeleteSellOfferMessageEnvelope struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          int32                   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       int32                   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Payload       *DeleteSellOfferMessage `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                  `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                  `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSellOfferMessageEnvelope) Reset() {
	*x = DeleteSellOfferMessageEnvelope{}
	mi := &file_pkg_protocol_sell_offers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSellOfferMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellOfferMessageEnvelope) ProtoMessage() {}

func (x *DeleteSellOfferMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_sell_offers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSellOfferMessageEnvelope.ProtoReflect.Descriptor instead.
func (*DeleteSellOfferMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_sell_offers_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSellOfferMessageEnvelope) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DeleteSellOfferMessageEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DeleteSellOfferMessageEnvelope) GetPayload() *DeleteSellOfferMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeleteSellOfferMessageEnvelope) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DeleteSellOfferMessageEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_pkg_protocol_sell_offers_proto protoreflect.FileDescriptor

const file_pkg_protocol_sell_offers_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/protocol/sell_offers.proto\x12\rfractalengine\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n" +
	"\x18SellOfferMessageEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x129\n" +
	"\apayload\x18\x03 \x01(\v2\x1f.fractalengine.SellOfferMessageR\apayload\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\"\xac\x01\n" +
	"\x10SellOfferMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x129\n" +
	"\apayload\x18\x03 \x01(\v2\x1f.fractalengine.SellOfferPayloadR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8a\x01\n" +
	"\x10SellOfferPayload\x12'\n" +
	"\x0fofferer_address\x18\x01 \x01(\tR\x0eoffererAddress\x12\x1b\n" +
	"\tmint_hash\x18\x02 \x01(\tR\bmintHash\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\",\n" +
	"\x16DeleteSellOfferMessage\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\xcc\x01\n" +
	"\x1eDeleteSellOfferMessageEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12?\n" +
	"\apayload\x18\x03 \x01(\v2%.fractalengine.DeleteSellOfferMessageR\apayload\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignatureB\x0eZ\fpkg/protocolb\x06proto3"

var (
	file_pkg_protocol_sell_offers_proto_rawDescOnce sync.Once
	file_pkg_protocol_sell_offers_proto_rawDescData []byte
)

func file_pkg_protocol_sell_offers_proto_rawDescGZIP() []byte {
	file_pkg_protocol_sell_offers_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_sell_offers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_sell_offers_proto_rawDesc), len(file_pkg_protocol_sell_offers_proto_rawDesc)))
	})
	return file_pkg_protocol_sell_offers_proto_rawDescData
}

var file_pkg_protocol_sell_offers_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_protocol_sell_offers_proto_goTypes = []any{
	(*SellOfferMessageEnvelope)(nil),       // 0: fractalengine.SellOfferMessageEnvelope
	(*SellOfferMessage)(nil),               // 1: fractalengine.SellOfferMessage
	(*SellOfferPayload)(nil),               // 2: fractalengine.SellOfferPayload
	(*DeleteSellOfferMessage)(nil),         // 3: fractalengine.DeleteSellOfferMessage
	(*DeleteSellOfferMessageEnvelope)(nil), // 4: fractalengine.DeleteSellOfferMessageEnvelope
	(*timestamppb.Timestamp)(nil),          // 5: google.protobuf.Timestamp
}
var file_pkg_protocol_sell_offers_proto_depIdxs = []int32{
	1, // 0: fractalengine.SellOfferMessageEnvelope.payload:type_name -> fractalengine.SellOfferMessage
	2, // 1: fractalengine.SellOfferMessage.payload:type_name -> fractalengine.SellOfferPayload
	5, // 2: fractalengine.SellOfferMessage.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: fractalengine.DeleteSellOfferMessageEnvelope.payload:type_name -> fractalengine.DeleteSellOfferMessage
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_protocol_sell_offers_proto_init() }
func file_pkg_protocol_sell_offers_proto_init() {
	if File_pkg_protocol_sell_offers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_sell_offers_proto_rawDesc), len(file_pkg_protocol_sell_offers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_sell_offers_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_sell_offers_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_sell_offers_proto_msgTypes,
	}.Build()
	File_pkg_protocol_sell_offers_proto = out.File
	file_pkg_protocol_sell_offers_proto_goTypes = nil
	file_pkg_protocol_sell_offers_proto_depIdxs = nil
}
