sequenceDiagram
    participant Processor as Fractal Engine Processor
    participant Store as Fractal Store

loop Every 5 seconds
    Processor->>Store: Fetch Onchain transactions (Invoices)
    Processor->>Store: Check if Invoice Has Pending Token Balance
    alt Has Pending Token Balance
        Processor->>Store: Match Unconfirmed Invoice with Onchain Transaction
        Processor->>Store: Save Invoice
        Processor->>Store: Set Payment Address on Invoice
        Processor->>Store: Delete Onchain Transaction
        Processor->>Store: Delete Unconfirmed Invoice
    end
end

 