sequenceDiagram
    Frank->>Fractal API: View sell offers for mint
    Fractal API-->>Frank: Sell offers for mint
    Frank->>Fractal API: Create a buy offer for mint
    Fractal API->>Fractal Store: Write buy offer
    Fractal API->>DogeNet: Gossip buy offer