sequenceDiagram
    Bob->>Fractal API: View buy offers for mint
    Fractal API-->>Bob: Buy offers for mint
    Bob->>Fractal API: Create invoice (from buy offer)
    Fractal API->>Fractal Store: Check rollups to ensure availability for invoice
    Fractal API->>Fractal Store: Write unconfirmed invoice
    Fractal API->>DogeNet: Gossip unconfirmed invoice
    Fractal API-->>Bob: Encoded invoice payload to write on chain
    Bob->>L1: Write invoice payload on chain
    L1->>Fractal Follower: On Invoice FE Transaction
    Fractal Follower->>Fractal Store: Validate and confirm Invoice
    Fractal Follower->>Fractal Store: Update Invoice so that pay too address is now visible
    Fractal Follower->>Fractal Store: Update Rollups