// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/mints": {
            "get": {
                "description": "Returns a list of mints",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mints"
                ],
                "summary": "Get all mints",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_rpc.GetMintsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new mint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mints"
                ],
                "summary": "Create a mint",
                "parameters": [
                    {
                        "description": "Mint request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_rpc.CreateMintRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/pkg_rpc.CreateMintResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/offers": {
            "post": {
                "description": "Creates a new offer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "offers"
                ],
                "summary": "Create an offer",
                "parameters": [
                    {
                        "description": "Offer request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_rpc.CreateOfferRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/pkg_rpc.CreateOfferResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dogecoin_org_fractal-engine_pkg_store.Mint": {
            "type": "object",
            "properties": {
                "block_height": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "feed_url": {
                    "type": "string"
                },
                "fraction_count": {
                    "type": "integer"
                },
                "hash": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lockup_options": {
                    "$ref": "#/definitions/dogecoin_org_fractal-engine_pkg_store.StringInterfaceMap"
                },
                "metadata": {
                    "$ref": "#/definitions/dogecoin_org_fractal-engine_pkg_store.StringInterfaceMap"
                },
                "owner_address": {
                    "type": "string"
                },
                "requirements": {
                    "$ref": "#/definitions/dogecoin_org_fractal-engine_pkg_store.StringInterfaceMap"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "transaction_hash": {
                    "$ref": "#/definitions/sql.NullString"
                }
            }
        },
        "dogecoin_org_fractal-engine_pkg_store.OfferType": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "OfferTypeBuy",
                "OfferTypeSell"
            ]
        },
        "dogecoin_org_fractal-engine_pkg_store.StringInterfaceMap": {
            "type": "object",
            "additionalProperties": true
        },
        "pkg_rpc.CreateMintRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "feed_url": {
                    "type": "string"
                },
                "fraction_count": {
                    "type": "integer"
                },
                "lockup_options": {
                    "$ref": "#/definitions/dogecoin_org_fractal-engine_pkg_store.StringInterfaceMap"
                },
                "metadata": {
                    "$ref": "#/definitions/dogecoin_org_fractal-engine_pkg_store.StringInterfaceMap"
                },
                "owner_address": {
                    "type": "string"
                },
                "requirements": {
                    "$ref": "#/definitions/dogecoin_org_fractal-engine_pkg_store.StringInterfaceMap"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "pkg_rpc.CreateMintResponse": {
            "type": "object",
            "properties": {
                "encoded_transaction_body": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "transaction_hash": {
                    "type": "string"
                }
            }
        },
        "pkg_rpc.CreateOfferRequest": {
            "type": "object",
            "properties": {
                "mint_hash": {
                    "type": "string"
                },
                "offerer_address": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/dogecoin_org_fractal-engine_pkg_store.OfferType"
                }
            }
        },
        "pkg_rpc.CreateOfferResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "pkg_rpc.GetMintsResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "mints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dogecoin_org_fractal-engine_pkg_store.Mint"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "sql.NullString": {
            "type": "object",
            "properties": {
                "string": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if String is not NULL",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Fractal Engine API",
	Description:      "API for managing mints and offers",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
