name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Enable Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Tidy modules
        run: nix run .#tidy

      - name: Format
        run: nix run .#format

      - name: Lint
        run: nix run .#lint

      - name: Run tests
        env:
          GO_TEST_EXTRA_FLAGS: "-race"
        run: nix run .#test

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.txt
